<script setup lang="ts">
import { onMounted, ref } from "vue";
interface Repair { id: string; brand: string; model: string; }
interface Payment { id: string; repairOrderId: string; amountCents: number; method: string; status: string; reference: string | null; createdAt: string; }
const props = defineProps<{ accessToken: string }>(); const repairs = ref<Repair[]>([]); const payments = ref<Payment[]>([]); const form = ref({ repairOrderId: "", amountCents: 0, method: "card", reference: "" }); const loading = ref(false); const errorMessage = ref(""); const successMessage = ref("");
function headers(json = false): HeadersInit { return json ? { "content-type": "application/json", authorization: `Bearer ${props.accessToken}` } : { authorization: `Bearer ${props.accessToken}` }; }
function money(cents: number): string { return new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" }).format(cents / 100); }
function repairName(id: string): string { const repair = repairs.value.find((item) => item.id === id); return repair ? `${repair.brand} ${repair.model}` : id.slice(0, 8); }
async function request(url: string, options: RequestInit = {}): Promise<Response> { return fetch(url, { ...options, headers: { ...headers(Boolean(options.body)), ...(options.headers ?? {}) } }); }
async function load(): Promise<void> { loading.value = true; errorMessage.value = ""; try { const [repairsResponse, paymentsResponse] = await Promise.all([request("/api/repairs"), request("/api/payments")]); if (!repairsResponse.ok || !paymentsResponse.ok) throw new Error("No se pudo cargar el TPV."); repairs.value = await repairsResponse.json(); payments.value = await paymentsResponse.json(); } catch (error) { errorMessage.value = (error as Error).message; } finally { loading.value = false; } }
async function createPayment(): Promise<void> { const response = await request("/api/payments", { method: "POST", body: JSON.stringify(form.value) }); if (!response.ok) { errorMessage.value = "No se pudo registrar el cobro."; return; } successMessage.value = "Cobro registrado."; form.value = { repairOrderId: "", amountCents: 0, method: "card", reference: "" }; await load(); }
async function refund(payment: Payment): Promise<void> { const response = await request(`/api/payments/${payment.id}/refund`, { method: "POST" }); if (!response.ok) { errorMessage.value = "No se pudo reembolsar el cobro."; return; } successMessage.value = "Cobro reembolsado."; await load(); }
onMounted(load);
</script>

<template>
  <section class="operations-view content"><header><div><p class="eyebrow">TPV</p><h1>Cobros</h1></div><button type="button" :disabled="loading" @click="load">Actualizar</button></header><p v-if="errorMessage" class="feedback error">{{ errorMessage }}</p><p v-if="successMessage" class="feedback success">{{ successMessage }}</p><div class="operations-grid"><form class="operation-panel operation-form" @submit.prevent="createPayment"><p class="eyebrow">Nuevo cobro</p><h2>Registrar pago</h2><label><span>Reparación</span><select v-model="form.repairOrderId" required><option disabled value="">Selecciona orden</option><option v-for="repair in repairs" :key="repair.id" :value="repair.id">{{ repair.brand }} {{ repair.model }}</option></select></label><label><span>Importe (céntimos)</span><input v-model.number="form.amountCents" min="1" type="number" required /></label><label><span>Método</span><select v-model="form.method"><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option></select></label><label><span>Referencia</span><input v-model="form.reference" /></label><button type="submit">Registrar cobro</button></form><section class="operation-panel"><div class="section-heading"><div><p class="eyebrow">Historial</p><h2>Pagos registrados</h2></div><span class="count">{{ payments.length }}</span></div><p v-if="!payments.length" class="empty">No hay pagos registrados.</p><ul class="operation-list"><li v-for="payment in payments" :key="payment.id"><div><strong>{{ money(payment.amountCents) }}</strong><span>{{ repairName(payment.repairOrderId) }} · {{ payment.method }} · {{ payment.status }}</span></div><button v-if="payment.status === 'paid'" type="button" class="secondary" @click="refund(payment)">Reembolsar</button></li></ul></section></div></section>
</template>
