<script setup lang="ts">
import { onMounted, ref } from "vue";
interface Repair { id: string; brand: string; model: string; }
interface Payment { id: string; repairOrderId: string; amountCents: number; method: string; status: string; reference: string | null; createdAt: string; }
interface PaymentSummary { date: string; paidCents: number; refundedCents: number; netCents: number; byMethod: Record<string, { paidCents: number; refundedCents: number; netCents: number }>; }
interface CashRegister { businessDate: string; status: "open" | "closed"; paidCents: number; refundedCents: number; netCents: number; }
const props = defineProps<{ accessToken: string }>(); const repairs = ref<Repair[]>([]); const payments = ref<Payment[]>([]); const summary = ref<PaymentSummary | null>(null); const cashRegister = ref<CashRegister | null>(null); const form = ref({ repairOrderId: "", amountCents: 0, method: "card", reference: "" }); const loading = ref(false); const errorMessage = ref(""); const successMessage = ref("");
function headers(json = false): HeadersInit { return json ? { "content-type": "application/json", authorization: `Bearer ${props.accessToken}` } : { authorization: `Bearer ${props.accessToken}` }; }
function money(cents: number): string { return new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" }).format(cents / 100); }
function repairName(id: string): string { const repair = repairs.value.find((item) => item.id === id); return repair ? `${repair.brand} ${repair.model}` : id.slice(0, 8); }
async function request(url: string, options: RequestInit = {}): Promise<Response> { return fetch(url, { ...options, headers: { ...headers(Boolean(options.body)), ...(options.headers ?? {}) } }); }
async function load(): Promise<void> { loading.value = true; errorMessage.value = ""; try { const today = new Date().toISOString().slice(0, 10); const [repairsResponse, paymentsResponse, summaryResponse, cashResponse] = await Promise.all([request("/api/repairs"), request("/api/payments"), request(`/api/payments/summary/${today}`), request(`/api/payments/cash-register/${today}`)]); if (!repairsResponse.ok || !paymentsResponse.ok || !summaryResponse.ok) throw new Error("No se pudo cargar el TPV."); repairs.value = await repairsResponse.json(); payments.value = await paymentsResponse.json(); summary.value = await summaryResponse.json(); cashRegister.value = cashResponse.ok ? await cashResponse.json() : null; } catch (error) { errorMessage.value = (error as Error).message; } finally { loading.value = false; } }
async function createPayment(): Promise<void> { const response = await request("/api/payments", { method: "POST", body: JSON.stringify(form.value) }); if (!response.ok) { errorMessage.value = "No se pudo registrar el cobro."; return; } successMessage.value = "Cobro registrado."; form.value = { repairOrderId: "", amountCents: 0, method: "card", reference: "" }; await load(); }
async function refund(payment: Payment): Promise<void> { const response = await request(`/api/payments/${payment.id}/refund`, { method: "POST" }); if (!response.ok) { errorMessage.value = "No se pudo reembolsar el cobro."; return; } successMessage.value = "Cobro reembolsado."; await load(); }
async function openCashRegister(): Promise<void> { const date = new Date().toISOString().slice(0, 10); const response = await request(`/api/payments/cash-register/${date}/open`, { method: "POST" }); if (!response.ok) { errorMessage.value = "No se pudo abrir la caja."; return; } successMessage.value = "Caja abierta."; await load(); }
async function closeCashRegister(): Promise<void> { const date = new Date().toISOString().slice(0, 10); const response = await request(`/api/payments/cash-register/${date}/close`, { method: "POST" }); if (!response.ok) { errorMessage.value = "No se pudo cerrar la caja."; return; } successMessage.value = "Caja cerrada."; await load(); }
async function downloadReceipt(paymentId: string): Promise<void> { const response = await request(`/api/payments/${paymentId}/pdf`); if (!response.ok) { errorMessage.value = "No se pudo descargar el recibo."; return; } const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `receipt-${paymentId.slice(0, 8)}.pdf`; anchor.click(); URL.revokeObjectURL(url); }
onMounted(load);
</script>

<template>
  <section class="operations-view content">
    <header><div><p class="eyebrow">TPV</p><h1>Cobros</h1></div><button type="button" :disabled="loading" @click="load">Actualizar</button></header>
    <section class="cash-register-panel operation-panel"><div><p class="eyebrow">Caja diaria</p><h2>{{ cashRegister?.status === "closed" ? "Caja cerrada" : cashRegister?.status === "open" ? "Caja abierta" : "Sin apertura" }}</h2></div><div class="cash-register-actions"><button v-if="!cashRegister" type="button" @click="openCashRegister">Abrir caja</button><button v-else-if="cashRegister.status === 'open'" type="button" @click="closeCashRegister">Cerrar caja</button><span v-if="cashRegister">Neto: {{ money(cashRegister.netCents) }}</span></div></section>
    <p v-if="errorMessage" class="feedback error">{{ errorMessage }}</p><p v-if="successMessage" class="feedback success">{{ successMessage }}</p>
    <section v-if="summary" class="payment-summary"><article class="metric green"><span>Cobrado hoy</span><strong>{{ money(summary.paidCents) }}</strong></article><article class="metric amber"><span>Reembolsado</span><strong>{{ money(summary.refundedCents) }}</strong></article><article class="metric blue"><span>Neto</span><strong>{{ money(summary.netCents) }}</strong></article></section>
    <div class="operations-grid"><form class="operation-panel operation-form" @submit.prevent="createPayment"><p class="eyebrow">Nuevo cobro</p><h2>Registrar pago</h2><label><span>Reparación</span><select v-model="form.repairOrderId" required><option disabled value="">Selecciona orden</option><option v-for="repair in repairs" :key="repair.id" :value="repair.id">{{ repair.brand }} {{ repair.model }}</option></select></label><label><span>Importe (céntimos)</span><input v-model.number="form.amountCents" min="1" type="number" required /></label><label><span>Método</span><select v-model="form.method"><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option></select></label><label><span>Referencia</span><input v-model="form.reference" /></label><button type="submit">Registrar cobro</button></form><section class="operation-panel"><div class="section-heading"><div><p class="eyebrow">Historial</p><h2>Pagos registrados</h2></div><span class="count">{{ payments.length }}</span></div><p v-if="!payments.length" class="empty">No hay pagos registrados.</p><ul class="operation-list"><li v-for="payment in payments" :key="payment.id"><div><strong>{{ money(payment.amountCents) }}</strong><span>{{ repairName(payment.repairOrderId) }} · {{ payment.method }} · {{ payment.status }}</span></div><button v-if="payment.status === 'paid'" type="button" class="secondary" @click="refund(payment)">Reembolsar</button></li></ul></section></div>
  </section>
</template>
