<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import { createPayment, listRepairs, type InvoiceLine, type Payment } from "../api";
const router = useRouter();
const repairs = ref<{ id: string; brand: string; model: string }[]>([]);
const form = ref<{ repairOrderId: string; method: Payment["method"]; reference: string; invoiceLines: InvoiceLine[] }>({ repairOrderId: "", method: "card", reference: "", invoiceLines: [{ concept: "Servicio de reparacion", quantity: 1, unitPriceCents: 0, discountPercent: 0, taxRate: 21 }] });
const error = ref("");
const lineNet = (line: InvoiceLine) => Math.round(line.quantity * line.unitPriceCents * (1 - line.discountPercent / 100));
const totalCents = computed(() => form.value.invoiceLines.reduce((total, line) => { const net = lineNet(line); return total + net + Math.round(net * line.taxRate / 100); }, 0));
function addLine(): void { form.value.invoiceLines.push({ concept: "", quantity: 1, unitPriceCents: 0, discountPercent: 0, taxRate: 21 }); }
function removeLine(index: number): void { if (form.value.invoiceLines.length > 1) form.value.invoiceLines.splice(index, 1); }
function money(cents: number): string { return new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" }).format(cents / 100); }
onMounted(async () => { repairs.value = await listRepairs(); });
async function save(): Promise<void> { try { const payment = await createPayment({ repairOrderId: form.value.repairOrderId, amountCents: totalCents.value, method: form.value.method, reference: form.value.reference, invoiceLines: form.value.invoiceLines }); void router.push({ name: "payments.detail", params: { id: payment.id } }); } catch (reason) { error.value = (reason as Error).message; } }
</script>
<template><form class="entity-form invoice-form" @submit.prevent="save"><header><div><p class="eyebrow">TPV</p><h1>Registrar cobro y factura</h1></div></header><fieldset><legend>Datos del cobro</legend><label>Reparacion<select v-model="form.repairOrderId" required><option disabled value="">Selecciona una orden</option><option v-for="repair in repairs" :key="repair.id" :value="repair.id">{{ repair.brand }} {{ repair.model }}</option></select></label><label>Metodo<select v-model="form.method"><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option></select></label><label>Referencia<input v-model="form.reference" /></label></fieldset><fieldset><legend>Lineas de factura</legend><div class="invoice-line-editor" v-for="(line, index) in form.invoiceLines" :key="index"><input v-model="line.code" placeholder="Codigo" /><input v-model="line.concept" required placeholder="Concepto" /><input v-model.number="line.quantity" type="number" min="0.01" step="0.01" required placeholder="Unidades" /><input v-model.number="line.unitPriceCents" type="number" min="0" required placeholder="Precio (cent.)" /><input v-model.number="line.discountPercent" type="number" min="0" max="100" step="0.01" placeholder="Dto. %" /><button class="secondary" type="button" :disabled="form.invoiceLines.length === 1" @click="removeLine(index)">Quitar</button><output>{{ money(lineNet(line) + Math.round(lineNet(line) * line.taxRate / 100)) }}</output></div><button class="secondary" type="button" @click="addLine">Anadir linea</button></fieldset><p class="invoice-total">Total factura: <strong>{{ money(totalCents) }}</strong></p><p v-if="error" class="feedback error">{{ error }}</p><footer><button class="secondary" type="button" @click="router.back()">Cancelar</button><button :disabled="!totalCents">Registrar cobro</button></footer></form></template>