<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { listCustomers, type Customer } from "../api";
const route = useRoute(); const router = useRouter(); const customers = ref<Customer[]>([]); const loading = ref(true); const error = ref("");
const query = ref(String(route.query.q ?? "")); const status = ref(String(route.query.estado ?? "")); const tag = ref(String(route.query.etiqueta ?? "")); let debounce: number | undefined;
const filtered = computed(() => customers.value.filter((customer) => { const searchable = `${customer.displayName} ${customer.email ?? ""} ${customer.phone ?? ""} ${customer.taxId ?? ""}`.toLowerCase(); return (!query.value || searchable.includes(query.value.toLowerCase())) && (!status.value || customer.registrationStatus === status.value) && (!tag.value || customer.tags.includes(tag.value)); }));
const tags = computed(() => [...new Set(customers.value.flatMap((customer) => customer.tags))]);
async function load(): Promise<void> { loading.value = true; error.value = ""; try { customers.value = await listCustomers(); } catch (reason) { error.value = (reason as Error).message; } finally { loading.value = false; } }
function syncQuery(): void { window.clearTimeout(debounce); debounce = window.setTimeout(() => { void router.replace({ query: { q: query.value || undefined, estado: status.value || undefined, etiqueta: tag.value || undefined } }); }, 300); }
function clear(): void { query.value = ""; status.value = ""; tag.value = ""; }
watch([query, status, tag], syncQuery); onMounted(load);
</script>
<template><section class="customers-view"><header><div><p class="eyebrow">CRM</p><h1>Clientes <span class="count">{{ filtered.length }}</span></h1></div><RouterLink class="button-link" :to="{ name: 'customers.create' }">Nuevo cliente</RouterLink></header><div class="filter-bar"><input v-model="query" placeholder="Buscar por nombre, email, telefono o NIF" /><select v-model="status"><option value="">Todos los estados</option><option value="pending">Pendiente</option><option value="completed">Completado</option></select><select v-model="tag"><option value="">Todas las etiquetas</option><option v-for="item in tags" :key="item" :value="item">{{ item }}</option></select><button v-if="query || status || tag" class="secondary" type="button" @click="clear">Limpiar filtros</button></div><p v-if="error" class="feedback error">{{ error }} <button class="secondary" @click="load">Reintentar</button></p><div v-else class="customer-list"><div v-if="loading" class="skeleton-row" v-for="item in 5" :key="item" /><p v-else-if="!customers.length" class="empty">Aun no hay clientes registrados.</p><p v-else-if="!filtered.length" class="empty">Ningun cliente coincide con los filtros.</p><RouterLink v-else v-for="customer in filtered" :key="customer.id" class="customer-row" :to="{ name: 'customers.detail.general', params: { id: customer.id } }"><strong>{{ customer.displayName }}</strong><span>{{ customer.email || customer.phone || "Sin contacto" }}</span><span>{{ customer.tags.join(", ") || "Sin etiquetas" }}</span><span :class="['status-pill', customer.registrationStatus]">{{ customer.registrationStatus === "pending" ? "Pendiente" : "Completado" }}</span></RouterLink></div></section></template>