import type { FastifyRequest } from "fastify";
import { Body, Controller, Get, Param, Post, Req, Res } from "@xtaskjs/common";
import { InjectCommandBus, InjectQueryBus, type CommandBus, type QueryBus } from "@xtaskjs/cqrs";
import { Authenticated } from "@xtaskjs/security";
import { z } from "zod";
import { CreateTradeInRequestCommand, DecideTradeInRequestCommand, GetOwnTradeInRequestQuery, ListOwnTradeInRequestsQuery, SubmitTradeInRequestCommand } from "../../application/cqrs/ecommerce-messages.js";
import { TradeInPhotoRequiredError, TradeInTransitionError } from "../../application/trade-in-service.js";
import type { AuthTokenPayload } from "../../../users/infrastructure/http/auth-routes.js";
import { GetEcommerceAttachmentQuery, ListEcommerceAttachmentsQuery, UploadEcommerceAttachmentCommand } from "../../../attachments/application/cqrs/attachment-messages.js";
import { isAllowedAttachmentMimeType, type AttachmentUploaderRole } from "../../../attachments/domain/repair-attachment.js";

const requestSchema = z.object({ deviceType: z.enum(["console", "retro_console", "game", "phone", "tablet", "other"]), brand: z.string().trim().min(1).max(100), model: z.string().trim().min(1).max(160), conditionDescription: z.string().trim().min(1).max(10000) });
type ControllerReply = { code(statusCode: number): ControllerReply; header(name: string, value: string): ControllerReply; send(payload: unknown): unknown };

@Authenticated()
@Controller("/api/customer/trade-in-requests")
export class CustomerTradeInController {
  constructor(@InjectCommandBus() private readonly commandBus: CommandBus, @InjectQueryBus() private readonly queryBus: QueryBus) {}
  @Get() list(@Req() request: FastifyRequest, @Res() reply: ControllerReply): Promise<unknown> { const user = request.user as AuthTokenPayload; return user.role === "customer" ? this.queryBus.execute(new ListOwnTradeInRequestsQuery(user.sub)) : Promise.resolve(reply.code(403).send({ message: "Customer access required" })); }
  @Get("/:id") async get(@Param("id") id: string, @Req() request: FastifyRequest, @Res() reply: ControllerReply): Promise<unknown> { const user = request.user as AuthTokenPayload; if (user.role !== "customer") return reply.code(403).send({ message: "Customer access required" }); const result = await this.queryBus.execute(new GetOwnTradeInRequestQuery(id, user.sub)); return result ?? reply.code(404).send({ message: "Trade-in request not found" }); }
  @Get("/:id/attachments") async listAttachments(@Param("id") id: string, @Req() request: FastifyRequest, @Res() reply: ControllerReply): Promise<unknown> { if (!(await this.owned(id, request))) return reply.code(404).send({ message: "Trade-in request not found" }); return this.queryBus.execute(new ListEcommerceAttachmentsQuery("trade_in_request", id)); }
  @Post("/:id/attachments") async uploadAttachment(@Param("id") id: string, @Req() request: FastifyRequest, @Res() reply: ControllerReply): Promise<unknown> { const user = request.user as AuthTokenPayload; const tradeIn = await this.findOwn(id, request); if (!tradeIn) return reply.code(404).send({ message: "Trade-in request not found" }); if (tradeIn.status !== "draft") return reply.code(409).send({ message: "Attachments can only be added to a draft trade-in request" }); const upload = await request.file(); if (!upload) return reply.code(400).send({ message: "No file provided" }); if (!isAllowedAttachmentMimeType(upload.mimetype)) return reply.code(400).send({ message: "Unsupported file type" }); const attachment = await this.commandBus.execute(new UploadEcommerceAttachmentCommand("trade_in_request", id, user.sub, user.role as AttachmentUploaderRole, upload.filename, upload.mimetype, upload.file)); return attachment ? reply.code(201).send(attachment) : reply.code(404).send({ message: "Trade-in request not found" }); }
  @Get("/:id/attachments/:attachmentId") async downloadAttachment(@Param("id") id: string, @Param("attachmentId") attachmentId: string, @Req() request: FastifyRequest, @Res() reply: ControllerReply): Promise<unknown> { if (!(await this.owned(id, request))) return reply.code(404).send({ message: "Trade-in request not found" }); const download = await this.queryBus.execute(new GetEcommerceAttachmentQuery("trade_in_request", id, attachmentId)); if (!download) return reply.code(404).send({ message: "Attachment not found" }); reply.header("content-type", download.attachment.mimeType); reply.header("content-disposition", `inline; filename="${encodeURIComponent(download.attachment.fileName)}"`); return reply.send(download.buffer); }
  @Post() async create(@Body() body: unknown, @Req() request: FastifyRequest, @Res() reply: ControllerReply): Promise<unknown> { const user = request.user as AuthTokenPayload; if (user.role !== "customer") return reply.code(403).send({ message: "Customer access required" }); const parsed = requestSchema.safeParse(body); return parsed.success ? reply.code(201).send(await this.commandBus.execute(new CreateTradeInRequestCommand(user.sub, parsed.data))) : reply.code(400).send({ message: "Invalid trade-in request", issues: parsed.error.flatten() }); }
  @Post("/:id/submit") async submit(@Param("id") id: string, @Req() request: FastifyRequest, @Res() reply: ControllerReply): Promise<unknown> { const user = request.user as AuthTokenPayload; if (user.role !== "customer") return reply.code(403).send({ message: "Customer access required" }); try { const tradeIn = await this.commandBus.execute(new SubmitTradeInRequestCommand(id, user.sub)); return tradeIn ?? reply.code(404).send({ message: "Trade-in request not found" }); } catch (error) { if (error instanceof TradeInPhotoRequiredError || error instanceof TradeInTransitionError) return reply.code(409).send({ message: error.message }); throw error; } }
  @Post("/:id/accept") async accept(@Param("id") id: string, @Req() request: FastifyRequest, @Res() reply: ControllerReply): Promise<unknown> { return this.decide(id, "accepted", request, reply); }
  @Post("/:id/reject") async reject(@Param("id") id: string, @Req() request: FastifyRequest, @Res() reply: ControllerReply): Promise<unknown> { return this.decide(id, "rejected", request, reply); }
  private async decide(id: string, decision: "accepted" | "rejected", request: FastifyRequest, reply: ControllerReply): Promise<unknown> { const user = request.user as AuthTokenPayload; if (user.role !== "customer") return reply.code(403).send({ message: "Customer access required" }); try { const result = await this.commandBus.execute(new DecideTradeInRequestCommand(id, user.sub, decision)); return result ?? reply.code(404).send({ message: "Trade-in request not found" }); } catch (error) { if (error instanceof TradeInTransitionError) return reply.code(409).send({ message: error.message }); throw error; } }
  private async owned(id: string, request: FastifyRequest): Promise<boolean> { const user = request.user as AuthTokenPayload; return user.role === "customer" && Boolean(await this.queryBus.execute(new GetOwnTradeInRequestQuery(id, user.sub))); }
  private async findOwn(id: string, request: FastifyRequest): Promise<{ status: string } | undefined> { const user = request.user as AuthTokenPayload; return user.role === "customer" ? this.queryBus.execute(new GetOwnTradeInRequestQuery(id, user.sub)) as Promise<{ status: string } | undefined> : undefined; }
}
