import type { FastifyRequest } from "fastify";
import { Body, Controller, Get, Param, Patch, Post, Req, Res } from "@xtaskjs/common";
import { InjectCommandBus, InjectQueryBus, type CommandBus, type QueryBus } from "@xtaskjs/cqrs";
import { Authenticated } from "@xtaskjs/security";
import { z } from "zod";
import { CreateEcommerceProductCommand, GetEcommerceProductQuery, ListEcommerceOrdersQuery, ListEcommerceProductsQuery, UpdateEcommerceOrderStatusCommand, UpdateEcommerceProductCommand } from "../../application/cqrs/ecommerce-messages.js";
import { EcommerceOrderTransitionError } from "../../application/ecommerce-service.js";
import { PERMISSIONS } from "../../../users/domain/permission.js";
import { PermissionRequired } from "../../../users/infrastructure/http/permission-guard.js";
import { GetEcommerceAttachmentQuery, ListEcommerceAttachmentsQuery, UploadEcommerceAttachmentCommand } from "../../../attachments/application/cqrs/attachment-messages.js";
import { isAllowedAttachmentMimeType, type AttachmentUploaderRole } from "../../../attachments/domain/repair-attachment.js";
import type { AuthTokenPayload } from "../../../users/infrastructure/http/auth-routes.js";
import { GetEcommerceOrderInvoicePdf } from "../../application/get-ecommerce-order-invoice-pdf.js";
import { SendEcommerceOrderInvoiceEmail } from "../../application/send-ecommerce-order-invoice-email.js";

const categorySchema = z.enum(["console", "retro_console", "game", "phone", "tablet", "accessory", "other"]);
const conditionSchema = z.enum(["new", "refurbished", "used_good", "used_fair"]);
const productSchema = z.object({ sku: z.string().trim().min(1).max(120), title: z.string().trim().min(1).max(240), description: z.string().trim().min(1).max(10000), category: categorySchema, condition: conditionSchema, priceCents: z.number().int().nonnegative().max(100000000), stockQuantity: z.number().int().nonnegative().max(1000000), published: z.boolean().optional() });
const productsQuerySchema = z.object({ q: z.string().trim().min(1).max(160).optional(), category: categorySchema.optional(), published: z.enum(["true", "false"]).transform((value) => value === "true").optional(), pagina: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(25) });
const orderStatusSchema = z.object({ status: z.enum(["paid", "preparing", "shipped", "delivered", "cancelled", "refunded"]), paymentReference: z.string().trim().max(180).optional() });
const ordersQuerySchema = z.object({ status: z.enum(["pending_payment", "paid", "preparing", "shipped", "delivered", "cancelled", "refunded"]).optional(), pagina: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(25) });
type ControllerReply = { code(statusCode: number): ControllerReply; header(name: string, value: string): ControllerReply; send(payload: unknown): unknown };

@Authenticated()
@Controller("/api/ecommerce")
@PermissionRequired(PERMISSIONS.ecommerceManage)
export class EcommerceManagementController {
  constructor(@InjectCommandBus() private readonly commandBus: CommandBus, @InjectQueryBus() private readonly queryBus: QueryBus, private readonly getInvoicePdf: GetEcommerceOrderInvoicePdf, private readonly sendInvoiceEmail: SendEcommerceOrderInvoiceEmail) {}
  @Get("/products") listProducts(@Req() request: FastifyRequest, @Res() reply: ControllerReply): Promise<unknown> { const parsed = productsQuerySchema.safeParse(request.query); return parsed.success ? this.queryBus.execute(new ListEcommerceProductsQuery({ query: parsed.data.q, category: parsed.data.category, published: parsed.data.published, page: parsed.data.pagina, pageSize: parsed.data.pageSize })) : Promise.resolve(reply.code(400).send({ message: "Invalid ecommerce product list query", issues: parsed.error.flatten() })); }
  @Get("/products/:id") async getProduct(@Param("id") id: string, @Res() reply: ControllerReply): Promise<unknown> { const product = await this.queryBus.execute(new GetEcommerceProductQuery(id)); return product ?? reply.code(404).send({ message: "Product not found" }); }
  @Post("/products") async createProduct(@Body() body: unknown, @Res() reply: ControllerReply): Promise<unknown> { const parsed = productSchema.safeParse(body); return parsed.success ? reply.code(201).send(await this.commandBus.execute(new CreateEcommerceProductCommand(parsed.data))) : reply.code(400).send({ message: "Invalid product", issues: parsed.error.flatten() }); }
  @Patch("/products/:id") async updateProduct(@Param("id") id: string, @Body() body: unknown, @Res() reply: ControllerReply): Promise<unknown> { const parsed = productSchema.partial().refine((value) => Object.keys(value).length > 0).safeParse(body); if (!parsed.success) return reply.code(400).send({ message: "Invalid product", issues: parsed.error.flatten() }); const product = await this.commandBus.execute(new UpdateEcommerceProductCommand(id, parsed.data)); return product ?? reply.code(404).send({ message: "Product not found" }); }
  @Get("/products/:id/attachments") listProductAttachments(@Param("id") id: string): Promise<unknown> { return this.queryBus.execute(new ListEcommerceAttachmentsQuery("product", id)); }
  @Post("/products/:id/attachments") async uploadProductAttachment(@Param("id") id: string, @Req() request: FastifyRequest, @Res() reply: ControllerReply): Promise<unknown> { const upload = await request.file(); if (!upload) return reply.code(400).send({ message: "No file provided" }); if (!isAllowedAttachmentMimeType(upload.mimetype)) return reply.code(400).send({ message: "Unsupported file type" }); const user = request.user as AuthTokenPayload; const attachment = await this.commandBus.execute(new UploadEcommerceAttachmentCommand("product", id, user.sub, user.role as AttachmentUploaderRole, upload.filename, upload.mimetype, upload.file)); return attachment ? reply.code(201).send(attachment) : reply.code(404).send({ message: "Product not found" }); }
  @Get("/products/:id/attachments/:attachmentId") async downloadProductAttachment(@Param("id") id: string, @Param("attachmentId") attachmentId: string, @Res() reply: ControllerReply): Promise<unknown> { const download = await this.queryBus.execute(new GetEcommerceAttachmentQuery("product", id, attachmentId)); if (!download) return reply.code(404).send({ message: "Attachment not found" }); reply.header("content-type", download.attachment.mimeType); reply.header("content-disposition", `inline; filename="${encodeURIComponent(download.attachment.fileName)}"`); return reply.send(download.buffer); }
  @Get("/orders") listOrders(@Req() request: FastifyRequest, @Res() reply: ControllerReply): Promise<unknown> { const parsed = ordersQuerySchema.safeParse(request.query); return parsed.success ? this.queryBus.execute(new ListEcommerceOrdersQuery({ status: parsed.data.status, page: parsed.data.pagina, pageSize: parsed.data.pageSize })) : Promise.resolve(reply.code(400).send({ message: "Invalid ecommerce order list query", issues: parsed.error.flatten() })); }
  @Get("/orders/:id/invoice.pdf") async invoicePdf(@Param("id") id: string, @Res() reply: ControllerReply): Promise<unknown> { const document = await this.getInvoicePdf.execute(id); if (!document) return reply.code(404).send({ message: "Invoice not found" }); reply.header("content-type", "application/pdf"); reply.header("content-disposition", `attachment; filename="factura-${id.slice(0, 8)}.pdf"`); return reply.send(document); }
  @Patch("/orders/:id/status") async updateOrderStatus(@Param("id") id: string, @Body() body: unknown, @Res() reply: ControllerReply): Promise<unknown> { const parsed = orderStatusSchema.safeParse(body); if (!parsed.success) return reply.code(400).send({ message: "Invalid order status", issues: parsed.error.flatten() }); try { const order = await this.commandBus.execute(new UpdateEcommerceOrderStatusCommand(id, parsed.data.status, parsed.data.paymentReference)); if (!order) return reply.code(404).send({ message: "Order not found" }); if (parsed.data.status === "paid") { try { await this.sendInvoiceEmail.execute(id); } catch (error) { console.warn("Ecommerce invoice email could not be sent", error); } } return order; } catch (error) { if (error instanceof EcommerceOrderTransitionError) return reply.code(409).send({ message: error.message }); throw error; } }
}
