import { staffSession } from "../auth/session";
export interface Item { id: string; sku: string; name: string; description: string | null; unit: string; stock: number; minimumStock: number; }
export interface Movement { id: string; inventoryItemId: string; repairOrderId: string | null; quantity: number; type: string; note: string | null; createdAt: string; }
export interface Supplier { id: string; name: string; email: string | null; phone: string | null; notes: string | null; }
export interface PurchaseOrder { id: string; supplierId: string; status: string; lines: { inventoryItemId: string; quantity: number; unitCostCents: number }[]; }
const headers = (): HeadersInit => ({ "content-type": "application/json", authorization: `Bearer ${staffSession.value?.accessToken ?? ""}` });
async function request<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { ...headers(), ...init?.headers } }); if (!response.ok) throw new Error((await response.json().catch(() => ({ message: "No se pudo completar la operacion." }))).message); return response.json() as Promise<T>; }
export const listItems = () => request<Item[]>("/api/inventory"); export const lowStock = () => request<Item[]>("/api/inventory/alerts/low-stock"); export const getMovements = (id: string) => request<Movement[]>(`/api/inventory/${id}/movements`);
export const createItem = (input: { sku: string; name: string; description?: string; unit?: string; minimumStock?: number }) => request<Item>("/api/inventory", { method: "POST", body: JSON.stringify(input) }); export const adjustStock = (id: string, quantity: number) => request<Item>(`/api/inventory/${id}/stock`, { method: "PATCH", body: JSON.stringify({ quantity, type: "adjustment", note: "Ajuste desde almacen" }) });
export const listSuppliers = () => request<Supplier[]>("/api/inventory/suppliers"); export const createSupplier = (input: Omit<Supplier, "id">) => request<Supplier>("/api/inventory/suppliers", { method: "POST", body: JSON.stringify(input) }); export const listOrders = () => request<PurchaseOrder[]>("/api/inventory/purchase-orders"); export const createOrder = (input: { supplierId: string; lines: PurchaseOrder["lines"] }) => request<PurchaseOrder>("/api/inventory/purchase-orders", { method: "POST", body: JSON.stringify(input) }); export const receiveOrder = (id: string) => request<PurchaseOrder>(`/api/inventory/purchase-orders/${id}/receive`, { method: "POST" });