<script setup lang="ts">
import { onMounted, ref } from "vue";
import { staffSession } from "../../auth/session";
import { listStores, type Store } from "../api";
import RepairStatusDonut from "../components/RepairStatusDonut.vue";

type Count = { status?: string; name?: string; count: number }; type Summary = { newCustomers: number; lowStock: number; paidSales: { count: number; cents: number }; repairsByStatus: Count[]; purchaseOrdersByStatus: Count[]; technicians: Count[]; };
const stores = ref<Store[]>([]); const storeId = ref(""); const from = ref(new Date(Date.now() - 30 * 86400000).toISOString().slice(0, 10)); const to = ref(new Date().toISOString().slice(0, 10)); const summary = ref<Summary | null>(null); const error = ref("");
async function load(): Promise<void> { try { error.value = ""; const query = new URLSearchParams({ from: from.value, to: to.value }); if (storeId.value) query.set("storeId", storeId.value); const response = await fetch(`/api/admin/dashboard/summary?${query}`, { headers: { authorization: `Bearer ${staffSession.value?.accessToken ?? ""}` } }); if (!response.ok) throw new Error((await response.json().catch(() => ({ message: "No se pudo cargar el panel." }))).message); summary.value = await response.json() as Summary; } catch (reason) { error.value = (reason as Error).message; } }
onMounted(async () => { if (staffSession.value?.user.role === "admin") stores.value = (await listStores()).filter((store) => store.active); await load(); });
function width(rows: Count[], value: number): string { return `${Math.max(8, Math.round((value / Math.max(...rows.map((row) => row.count), 1)) * 100))}%`; }
function euros(cents: number): string { return new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" }).format(cents / 100); }
</script>
<template><section><header><div><p class="eyebrow">Administracion</p><h1>Panel principal</h1></div></header><form class="filter-bar" @submit.prevent="load"><select v-if="staffSession?.user.role === 'admin'" v-model="storeId"><option value="">Todas las tiendas</option><option v-for="store in stores" :key="store.id" :value="store.id">{{ store.name }}</option></select><input v-model="from" type="date" aria-label="Desde" /><input v-model="to" type="date" aria-label="Hasta" /><button>Actualizar</button></form><p v-if="error" class="feedback error">{{ error }}</p><template v-if="summary"><div class="dashboard-metrics"><article><span>Ventas cobradas</span><strong>{{ euros(summary.paidSales.cents) }}</strong><small>{{ summary.paidSales.count }} cobros</small></article><article><span>Clientes nuevos</span><strong>{{ summary.newCustomers }}</strong></article><article><span>Alertas de stock</span><strong>{{ summary.lowStock }}</strong></article></div><div class="dashboard-charts"><section><h2>Reparaciones por estado</h2><RepairStatusDonut :items="summary.repairsByStatus" /></section><section><h2>Técnicos con más reparaciones</h2><div v-for="technician in summary.technicians" :key="technician.name" class="chart-row"><span>{{ technician.name }}</span><div><i :style="{ width: width(summary.technicians, technician.count) }" /></div><strong>{{ technician.count }}</strong></div></section><section><h2>Pedidos de compra</h2><div v-for="order in summary.purchaseOrdersByStatus" :key="order.status" class="chart-row"><span>{{ order.status }}</span><div><i :style="{ width: width(summary.purchaseOrdersByStatus, order.count) }" /></div><strong>{{ order.count }}</strong></div></section></div></template></section></template>

<style scoped>
@media (max-width: 1100px) { .dashboard-charts { grid-template-columns: minmax(0, 1fr); } }
</style>