<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import { impersonateUser, listUsers, type AdminUser } from "../api";

const router = useRouter();
const users = ref<AdminUser[]>([]); const query = ref(""); const role = ref(""); const active = ref(""); const error = ref(""); const impersonating = ref("");
const filtered = computed(() => users.value.filter((user) => `${user.displayName} ${user.email}`.toLowerCase().includes(query.value.toLowerCase()) && (!role.value || user.role === role.value) && (!active.value || String(user.active) === active.value)));
onMounted(async () => { try { users.value = await listUsers(); } catch (reason) { error.value = (reason as Error).message; } });
async function impersonate(user: AdminUser): Promise<void> { impersonating.value = user.id; try { const session = await impersonateUser(user.id); window.localStorage.setItem("xtechjs.staff-session", JSON.stringify(session)); window.location.reload(); } catch (reason) { error.value = (reason as Error).message; } finally { impersonating.value = ""; } }
</script>
<template><section><header><div><p class="eyebrow">Administracion</p><h1>Usuarios <span class="count">{{ filtered.length }}</span></h1></div><RouterLink class="button-link" :to="{ name: 'admin.users.create' }">Nuevo usuario</RouterLink></header><div class="filter-bar"><input v-model="query" placeholder="Buscar por nombre o email" /><select v-model="role"><option value="">Todos los roles</option><option value="admin">Administrador</option><option value="technician">Tecnico</option><option value="customer">Cliente</option></select><select v-model="active"><option value="">Todos los estados</option><option value="true">Activos</option><option value="false">Inactivos</option></select></div><p v-if="error" class="feedback error">{{ error }}</p><div class="customer-list"><p v-if="!filtered.length" class="empty">No hay usuarios que coincidan.</p><RouterLink v-else v-for="user in filtered" :key="user.id" class="customer-row" :to="{ name: 'admin.users.detail.general', params: { id: user.id } }"><strong>{{ user.displayName }}</strong><span>{{ user.email }}</span><span>{{ user.role }}</span><span :class="['status-pill', user.active ? 'completed' : 'pending']">{{ user.active ? 'Activo' : 'Inactivo' }}</span><button v-if="user.role !== 'admin'" class="secondary" type="button" :disabled="impersonating === user.id" @click.prevent="impersonate(user)">{{ impersonating === user.id ? 'Entrando' : 'Suplantar' }}</button></RouterLink></div></section></template>