<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useRoute } from "vue-router";
import { completeManagedTradeInRequest, getManagedTradeInRequest, listManagedTradeInAttachments, proposeManagedTradeInRequest, reviewManagedTradeInRequest, type ShopAttachment, type TradeInRequest, type TradeInStatus } from "../api";

const route = useRoute();
const request = ref<TradeInRequest | null>(null);
const attachments = ref<ShopAttachment[]>([]);
const error = ref("");
const saving = ref(false);
const proposal = ref({ proposedAmountCents: 0, proposalNote: "" });
const completion = ref<{ finalAmountCents: number; method: "bank_transfer" | "cash"; reference: string }>({ finalAmountCents: 0, method: "bank_transfer", reference: "" });
const statusLabels: Record<TradeInStatus, string> = { draft: "Borrador", submitted: "Enviada", in_review: "En revisión", proposal_sent: "Propuesta enviada", accepted: "Aceptada", rejected: "Rechazada", completed: "Completada", cancelled: "Cancelada" };
const money = (cents: number) => new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" }).format(cents / 100);
async function load(): Promise<void> { error.value = ""; try { const id = String(route.params.id); const [loadedRequest, loadedAttachments] = await Promise.all([getManagedTradeInRequest(id), listManagedTradeInAttachments(id)]); request.value = loadedRequest; attachments.value = loadedAttachments; proposal.value.proposedAmountCents = loadedRequest.proposedAmountCents ?? 0; completion.value.finalAmountCents = loadedRequest.proposedAmountCents ?? 0; } catch (reason) { error.value = (reason as Error).message; } }
async function review(): Promise<void> { saving.value = true; error.value = ""; try { request.value = await reviewManagedTradeInRequest(String(route.params.id)); } catch (reason) { error.value = (reason as Error).message; } finally { saving.value = false; } }
async function propose(): Promise<void> { saving.value = true; error.value = ""; try { request.value = await proposeManagedTradeInRequest(String(route.params.id), { proposedAmountCents: proposal.value.proposedAmountCents, proposalNote: proposal.value.proposalNote || undefined }); } catch (reason) { error.value = (reason as Error).message; } finally { saving.value = false; } }
async function complete(): Promise<void> { saving.value = true; error.value = ""; try { request.value = await completeManagedTradeInRequest(String(route.params.id), { finalAmountCents: completion.value.finalAmountCents, method: completion.value.method, reference: completion.value.reference || undefined }); } catch (reason) { error.value = (reason as Error).message; } finally { saving.value = false; } }
onMounted(load);
</script>

<template>
  <section class="customer-order-detail"><p class="shop-back"><RouterLink :to="{ name: 'trade-in.list' }">Volver a valoraciones</RouterLink></p><p v-if="!request && !error" class="empty">Cargando solicitud...</p><p v-else-if="error && !request" class="feedback error">{{ error }}</p><template v-else-if="request"><header><div><p class="eyebrow">Compraventa</p><h1>{{ request.brand }} {{ request.model }}</h1><p>{{ request.deviceType }}</p></div><span :class="['status-pill', request.status]">{{ statusLabels[request.status] }}</span></header><div class="customer-order-detail-grid"><section><h2>Declaración del cliente</h2><p>{{ request.conditionDescription }}</p><p><strong>Recibida:</strong> {{ new Date(request.createdAt).toLocaleString('es-ES') }}</p></section><section><h2>Adjuntos</h2><ul v-if="attachments.length" class="ecommerce-attachment-list"><li v-for="attachment in attachments" :key="attachment.id">{{ attachment.fileName }} <span>{{ attachment.mimeType }}</span></li></ul><p v-else class="empty">No hay archivos adjuntos.</p></section></div><section v-if="request.status === 'submitted'" class="trade-in-workflow"><h2>Revisión</h2><button type="button" :disabled="saving" @click="review">{{ saving ? "Actualizando" : "Iniciar revisión" }}</button></section><form v-else-if="request.status === 'in_review'" class="entity-form ecommerce-product-form trade-in-workflow" @submit.prevent="propose"><h2>Enviar propuesta</h2><label>Importe propuesto (céntimos)<input v-model.number="proposal.proposedAmountCents" type="number" min="0" required /></label><label>Nota para el cliente<textarea v-model="proposal.proposalNote" maxlength="5000" rows="5" /></label><button :disabled="saving">{{ saving ? "Enviando" : "Enviar propuesta" }}</button></form><form v-else-if="request.status === 'accepted'" class="entity-form ecommerce-product-form trade-in-workflow" @submit.prevent="complete"><h2>Registrar pago</h2><div class="ecommerce-form-row"><label>Importe final (céntimos)<input v-model.number="completion.finalAmountCents" type="number" min="0" required /></label><label>Método<select v-model="completion.method"><option value="bank_transfer">Transferencia</option><option value="cash">Efectivo</option></select></label></div><label>Referencia<input v-model="completion.reference" maxlength="180" /></label><button :disabled="saving">{{ saving ? "Registrando" : "Registrar pago y cerrar" }}</button></form><section v-else-if="request.proposedAmountCents !== null" class="trade-in-workflow"><h2>Propuesta</h2><strong class="trade-in-amount">{{ money(request.proposedAmountCents) }}</strong><p v-if="request.proposalNote">{{ request.proposalNote }}</p><p v-if="request.finalAmountCents !== null"><strong>Pago final:</strong> {{ money(request.finalAmountCents) }}</p></section><p v-if="error" class="feedback error">{{ error }}</p></template></section>
</template>
